### ISSUE TITLE
Home to configure in HA ?

### ISSUE THREAD

**Issue by fulup-bzh** [sberthelot/teleinfo-home-assistant#2]
I placed component into ~/.homeassistant/custom_components/teleinfo. HA see and warn about it at boot time
```
Aug 05 11:10:40 raspberry systemd[1]: Started Home Assistant.
Aug 05 11:10:43 raspberry hass[1837]: 2022-08-05 11:10:43 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration enedis which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
```
Nevertheless I cannot find it from web integration UI. 
Question: how do we configure this componant for HA ?
Merci

**Comment by sberthelot** [comment]
Hi @fulup-bzh, the Warning is a standard message for custom integrations. There's a long way for this to become maybe some day a standard integration :)
Can you please review the new version along with the README instructions ?
Please note that is currently works out of the box only in "standard" TIC mode.

**Comment by fulup-bzh** [comment]
I understand the warning is normal, I listed it to show that the extension was effectively loaded. I will try your new configuration instruction and will let you known about the result.
Thank you for your support

**Comment by fulup-bzh** [comment]
Looks better with new config. Still a glich in config sample extension name. It is 'enedis' in the componant and 'teleinfo' in config sample.
``` sensor.yaml
platform: enedis
```
More problematic, while the extension successfully open serial port it still fail to initialise. As I do not see an option to select from 9600baud to 1200baud this might be the issue. 
```
ls -l /dev/ttyAMA0
crw-rw---- 1 root dialout 204, 64 Aug 11 12:26 /dev/ttyAMA0
```
Startup loop on initialisation.
```
tail -f home-assistant.log
2022-08-15 11:24:50.641 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration enedis which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-08-15 11:25:14.604 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform enedis is taking over 10 seconds.
...
2022-08-15 11:28:58.080 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: sensor.enedis
```

**Comment by fulup-bzh** [comment]
Switching from 9600 to 1200 initialisation succeeded, but with still an error within the log. Sensor is then visible within HA but with no value. I may ask EDF to change from legacy to 9600, but I'm also happy to make some test to help you extension to support both mode.
```
homeassistant@raspberry:~/.homeassistant $ tail -f home-assistant.log
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/template.py", line 537, in async_render_to_info
    render_info._result = self.async_render(variables, strict=strict, **kwargs)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/template.py", line 423, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: UndefinedError: 'None' has no attribute 'attributes'
2022-08-15 11:36:07.527 ERROR (MainThread) [homeassistant.helpers.template_entity] TemplateError('UndefinedError: 'None' has no attribute 'attributes'') while processing template 'Template("{{ states.sensor.enedis_teleinfo.attributes["PCOUP"] | int }}")' for attribute '_attr_native_value' in entity 'sensor.teleinfo_intensite_souscrite'
```
